-- Add detailed match statistics and odds to games table
-- Date: January 26, 2026

-- Odds columns
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_home NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_draw NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_away NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_over_15 NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_under_15 NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_over_25 NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_under_25 NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_over_35 NUMERIC(6,2);
ALTER TABLE games ADD COLUMN IF NOT EXISTS odds_under_35 NUMERIC(6,2);

-- Shot statistics
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_shots INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_shots INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_shots_on_target INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_shots_on_target INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_shots_off_target INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_shots_off_target INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_blocked_shots INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_blocked_shots INTEGER DEFAULT 0;

-- Game events
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_corners INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_corners INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_fouls INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_fouls INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_yellow_cards INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_yellow_cards INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_red_cards INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_red_cards INTEGER DEFAULT 0;

-- Advanced statistics
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_offsides INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_offsides INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_saves INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_saves INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_big_chances INTEGER DEFAULT 0;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_big_chances INTEGER DEFAULT 0;

-- Tactical information
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_formation TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_formation TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS home_days_rest INTEGER DEFAULT 7;
ALTER TABLE games ADD COLUMN IF NOT EXISTS away_days_rest INTEGER DEFAULT 7;

-- Match metadata
ALTER TABLE games ADD COLUMN IF NOT EXISTS referee_id INTEGER;
ALTER TABLE games ADD COLUMN IF NOT EXISTS match_events TEXT;
ALTER TABLE games ADD COLUMN IF NOT EXISTS flashscore_url TEXT;

-- Create indexes for commonly queried columns
CREATE INDEX IF NOT EXISTS idx_games_odds_home ON games(odds_home) WHERE odds_home IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_games_flashscore_url ON games(flashscore_url) WHERE flashscore_url IS NOT NULL;
